$wp = /home/alex/pictures/wp/wallpaper.png
# Preload is still required in the new version
preload = $wp

# The block syntax helps avoid "no target" errors
wallpaper {
    monitor = eDP-1
    path = $wp
}

# The block syntax helps avoid "no target" errors
wallpaper {
    monitor = DP-1
    path = $wp
}

# General settings
splash = false
ipc = on
