require("modules.monitors")
require("modules.autostart")
require("modules.environment")
require("modules.appearance")
require("modules.animations")
require("modules.devices")
require("modules.bindings")
