[general]
font-mono = "SF Mono"

[bar]
scale = 0.800000011920929

[[bar.layout]]
monitor = "*"
show = true
left = [
    "hyprland-workspaces",
    "media",
]
center = ["clock"]
right = [
    "battery",
    "volume",
    "bluetooth",
    "network",
    "notifications",
]

[styling.palette]
bg = "#11111b"
surface = "#181825"
elevated = "#1e1e2e"
fg = "#cdd6f4"
fg-muted = "#bac2de"
primary = "#b4befe"
red = "#f38ba8"
yellow = "#f9e2af"
green = "#a6e3a1"
blue = "#74c7ec"

[modules.bluetooth]
label-show = false

[modules.clock]
format = "%a %b %d %H:%M"

[modules.network]
label-show = false

[modules.notifications]
label-show = false
